### ISSUE TITLE
windows build link error

### ISSUE THREAD

**Issue by 1xinghuan** [LumaPictures/usd-qt#24]
I'm trying to build the luma outliner on windows. I used the latest dev package and there are lots of link errors when first building, I added some libs(pcp.lib arch.lib vt.lib) into link dependences but there are still 15 link errors:

2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::~SdfLayerStateDelegateBase(void)" (??1SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@UEAA@XZ) referenced in function "public: virtual void * __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::`scalar deleting destructor'(unsigned int)" (??_GUsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@UEAAPEAXI@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "public: void __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::SetField(class pxrInternal_v0_18__pxrReserved__::SdfAbstractDataSpecId const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::VtValue const &,class pxrInternal_v0_18__pxrReserved__::VtValue const *)" (?SetField@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@QEAAXAEBVSdfAbstractDataSpecId@2@AEBVTfToken@2@AEBVVtValue@2@PEBV52@@Z) referenced in function "private: bool __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_InvertSetField(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::VtValue const &)" (?_InvertSetField@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA_NAEBVSdfPath@2@AEBVTfToken@2@AEBVVtValue@2@@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "public: void __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::SetFieldDictValueByKey(class pxrInternal_v0_18__pxrReserved__::SdfAbstractDataSpecId const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::VtValue const &,class pxrInternal_v0_18__pxrReserved__::VtValue const *)" (?SetFieldDictValueByKey@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@QEAAXAEBVSdfAbstractDataSpecId@2@AEBVTfToken@2@1AEBVVtValue@2@PEBV52@@Z) referenced in function "private: bool __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_InvertSetFieldDictValueByKey(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::VtValue const &)" (?_InvertSetFieldDictValueByKey@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA_NAEBVSdfPath@2@AEBVTfToken@2@1AEBVVtValue@2@@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "public: void __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::SetTimeSample(class pxrInternal_v0_18__pxrReserved__::SdfAbstractDataSpecId const &,double,class pxrInternal_v0_18__pxrReserved__::VtValue const &)" (?SetTimeSample@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@QEAAXAEBVSdfAbstractDataSpecId@2@NAEBVVtValue@2@@Z) referenced in function "private: bool __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_InvertSetTimeSample(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,double,class pxrInternal_v0_18__pxrReserved__::VtValue const &)" (?_InvertSetTimeSample@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA_NAEBVSdfPath@2@NAEBVVtValue@2@@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "public: void __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::CreateSpec(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,enum pxrInternal_v0_18__pxrReserved__::SdfSpecType,bool)" (?CreateSpec@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@QEAAXAEBVSdfPath@2@W4SdfSpecType@2@_N@Z) referenced in function "private: bool __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_InvertDeleteSpec(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,bool,enum pxrInternal_v0_18__pxrReserved__::SdfSpecType,class pxrInternal_v0_18__pxrReserved__::TfRefPtr<class pxrInternal_v0_18__pxrReserved__::SdfData> const &)" (?_InvertDeleteSpec@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA_NAEBVSdfPath@2@_NW4SdfSpecType@2@AEBV?$TfRefPtr@VSdfData@pxrInternal_v0_18__pxrReserved__@@@2@@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "public: void __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::DeleteSpec(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,bool)" (?DeleteSpec@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@QEAAXAEBVSdfPath@2@_N@Z) referenced in function "private: bool __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_InvertCreateSpec(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,bool)" (?_InvertCreateSpec@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA_NAEBVSdfPath@2@_N@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "public: void __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::MoveSpec(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::SdfPath const &)" (?MoveSpec@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@QEAAXAEBVSdfPath@2@0@Z) referenced in function "private: bool __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_InvertMoveSpec(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::SdfPath const &)" (?_InvertMoveSpec@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA_NAEBVSdfPath@2@0@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "public: void __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::PushChild(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &)" (?PushChild@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@QEAAXAEBVSdfPath@2@AEBVTfToken@2@1@Z) referenced in function "private: bool __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_InvertPopTokenChild(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &)" (?_InvertPopTokenChild@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA_NAEBVSdfPath@2@AEBVTfToken@2@1@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "public: void __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::PushChild(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::SdfPath const &)" (?PushChild@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@QEAAXAEBVSdfPath@2@AEBVTfToken@2@0@Z) referenced in function "private: bool __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_InvertPopPathChild(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::SdfPath const &)" (?_InvertPopPathChild@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA_NAEBVSdfPath@2@AEBVTfToken@2@0@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "public: void __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::PopChild(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &)" (?PopChild@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@QEAAXAEBVSdfPath@2@AEBVTfToken@2@1@Z) referenced in function "private: bool __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_InvertPushTokenChild(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &)" (?_InvertPushTokenChild@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA_NAEBVSdfPath@2@AEBVTfToken@2@1@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "public: void __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::PopChild(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::SdfPath const &)" (?PopChild@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@QEAAXAEBVSdfPath@2@AEBVTfToken@2@0@Z) referenced in function "private: bool __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_InvertPushPathChild(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::SdfPath const &)" (?_InvertPushPathChild@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA_NAEBVSdfPath@2@AEBVTfToken@2@0@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "protected: __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::SdfLayerStateDelegateBase(void)" (??0SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@IEAA@XZ) referenced in function "private: __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::UsdQt_UndoStateDelegate(void)" (??0UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA@XZ)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "protected: class pxrInternal_v0_18__pxrReserved__::TfWeakPtr<class pxrInternal_v0_18__pxrReserved__::SdfLayer> __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::_GetLayer(void)const " (?_GetLayer@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@IEBA?AV?$TfWeakPtr@VSdfLayer@pxrInternal_v0_18__pxrReserved__@@@2@XZ) referenced in function "private: virtual void __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_OnDeleteSpec(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,bool)" (?_OnDeleteSpec@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@EEAAXAEBVSdfPath@2@_N@Z)
2>undoStateDelegate.obj : error LNK2019: unresolved external symbol "protected: class pxrInternal_v0_18__pxrReserved__::TfWeakPtr<class pxrInternal_v0_18__pxrReserved__::SdfAbstractData> __cdecl pxrInternal_v0_18__pxrReserved__::SdfLayerStateDelegateBase::_GetLayerData(void)const " (?_GetLayerData@SdfLayerStateDelegateBase@pxrInternal_v0_18__pxrReserved__@@IEBA?AV?$TfWeakPtr@VSdfAbstractData@pxrInternal_v0_18__pxrReserved__@@@2@XZ) referenced in function "private: bool __cdecl pxrInternal_v0_18__pxrReserved__::UsdQt_UndoStateDelegate::_InvertDeleteSpec(class pxrInternal_v0_18__pxrReserved__::SdfPath const &,bool,enum pxrInternal_v0_18__pxrReserved__::SdfSpecType,class pxrInternal_v0_18__pxrReserved__::TfRefPtr<class pxrInternal_v0_18__pxrReserved__::SdfData> const &)" (?_InvertDeleteSpec@UsdQt_UndoStateDelegate@pxrInternal_v0_18__pxrReserved__@@AEAA_NAEBVSdfPath@2@_NW4SdfSpecType@2@AEBV?$TfRefPtr@VSdfData@pxrInternal_v0_18__pxrReserved__@@@2@@Z)
2>undoStateDelegate.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl pxrInternal_v0_18__pxrReserved__::SdfData::Has(class pxrInternal_v0_18__pxrReserved__::SdfAbstractDataSpecId const &,class pxrInternal_v0_18__pxrReserved__::TfToken const &,class pxrInternal_v0_18__pxrReserved__::SdfAbstractDataValue *)const " (?Has@SdfData@pxrInternal_v0_18__pxrReserved__@@UEBA_NAEBVSdfAbstractDataSpecId@2@AEBVTfToken@2@PEAVSdfAbstractDataValue@2@@Z)

They are all from undoStateDelegate.
I'm using USD18.09 .

**Comment by 1xinghuan** [comment]
I ues the latest USD dev package and build successfully.

**Comment by EricHurdFVL** [comment]
I have this same issue, and it was not solved by the steps 1xinghuan executed.
