### ISSUE TITLE
build with boost 1_70

### ISSUE THREAD

**Issue by agelosc** [LumaPictures/usd-qt#35]
is it possible to build dev with boost 1_70 as of USD v20.05 or am I trying in vain?

I'm getting this output when trying to build:
```
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
-- Found Boost 1.70.0 at D:/software/tools/USD/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS python
-- Found boost_headers 1.70.0 at D:/software/tools/USD/lib/cmake/boost_headers-1.70.0
-- Found boost_python 1.70.0 at D:/software/tools/USD/lib/cmake/boost_python-1.70.0
-- No suitable boost_python variant has been identified!
--   boost_python27-vc141-mt-x64-1_70.lib (shared, Boost_USE_STATIC_LIBS=ON)
CMake Error at D:/software/tools/USD/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
  Found package configuration file:

    D:/software/tools/USD/lib/cmake/boost_python-1.70.0/boost_python-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

Call Stack (most recent call first):
  D:/software/tools/USD/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:444 (find_package)
  CMakeLists.txt:30 (find_package)


-- Configuring incomplete, errors occurred!
See also "D:/software/tools/usd-qt/CMakeFiles/CMakeOutput.log".
```

Thank you.

**Comment by nrusch** [comment]
Hi @agelosc ,

Unfortunately we are not building against Boost 1.70 yet, and we also do not use Windows, so you're in unfamiliar territory.

Based on that error, it looks like maybe you have dynamic Boost libs installed, but your usd-qt build is specifically looking for static libs? That's kind of a shot in the dark though...

**Comment by agelosc** [comment]
I'll try and build against USD 20.02 which if I remember correctly uses boost 1_65_1, not sure if windows is out of the question but I'll give it a go. Thanks for your time, I'm closing this question.

**Comment by Jinnm** [comment]
Hi，i have the same issue with python2.7.15, usd20.11, windows. Did you save the problem using USD 20.02?

**Comment by GreenEminence** [comment]
Have you tried setting `Boost_NO_BOOST_CMAKE=ON`?
