### ISSUE TITLE
Project compile issue

### ISSUE THREAD

**Issue by wandth** [LumaPictures/usd-qt#36]
Hello， I set some cmake variable and then compile it, it is success full, but when i open the sln project, and generate it it has two errors

![image](https://user-images.githubusercontent.com/34237282/121311759-4b618a80-c937-11eb-8e5f-3c1fd37e1579.png)

the environment is:
- boost 1.70.0
- mauausd 0.9
- usd 21.05
- python 2.7.18

**Comment by GreenEminence** [comment]
`UsdRelationship::BlockTargets` is deprecated and it was removed in USD 21.02.

You need to use `SetTargets({})`.

**Comment by nrusch** [comment]
Sorry for the delayed response on this, but I believe this should be updated in the latest master and dev updates.
