### ISSUE TITLE
ImportError: No module named types

### ISSUE THREAD

**Issue by looskoon** [LumaPictures/usd-qt#5]
When I run this:
python usdQt/app.py test.usd
I  got the error below:
/test/usd-qt-master/treemodel/itemtree.py", line 26, in <module>
    import pylib.types
ImportError: No module named types

and the module "pylib" is installed by pip install pylib.

**Comment by dgovil** [comment]
Running into the same thing. I don't see a pylib mentioned in the requirements.txt, and the only packages on pypi seem ambiguous. 

Any ideas if there is a specific package we can replace it with?

**Comment by dgovil** [comment]
We ended up replacing it with similar logic and it works now. Just wasn't certain if we missed any functionality but I don't think we did based on your reply.

Thank you for the information.

**Comment by chadrik** [comment]
Sorry about this bug.  We fixed it and it came back after a bad merge.  I've commented out the check since it's not strictly necessary.  This whole project will be going through a big refactor in the next few weeks, so we'll come back to the question of its necessity then.

**Comment by dgovil** [comment]
Thanks for the update, Chad!
