### ISSUE TITLE
Ability to provide a custom MenuBuilder

### ISSUE THREAD

**Issue by csaez** [LumaPictures/usd-qt#7]
Hi there,

In previous iterations we were able to seamlessly integrate our in-house commands into context menues by providing a custom MenuBuilder layering the in-house logic, unfortunately looks like this feature is not available anymore.

https://github.com/LumaPictures/usd-qt/blob/9d87cada5ad65fd118bbbc8a36db167f7d66f741/pxr/usdQt/qtUtils.py#L288

Do you envision a better way to integrate custom systems into context menus?
Otherwise, would it be possible to provide a setter of sorts so we can provide our own MenuBuilder externally?

Thanks!

**Comment by csaez** [comment]
Oh, scratch that... After further inspection, it looks like the new approach is to provide a custom OutlinerRole wrapping the execution of our in-house commands in MenuAction instances.

Sorry for the noise.

**Comment by nrusch** [comment]
Cool, glad you got it sorted.
